version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3307
    environment:
      MYSQL_USER: novousuario
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo: